logLevel: 'info'
maximumExecutionTime: '60m'
mode: Local
size: 4
topology: Line
persistence:
  kind: file
  path: /tmp/polkadot-lab.json
testCases:
- name: NumberOfPeers
  dependency:
    chart: w3f/polkadot-lab-test-case-number-of-peers
    version: "v0.1.0"
dependencies:
- chart: w3f/polkadot
  version: 'v0.27.3'
  values:
    image:
      repo: 'parity/polkadot'
      tag: 'v0.8.12'
